conversation/urls.py
from django.urls import path

from . import views

app_name = "conversation"

urlpatterns = [
    path("", views.inbox, name="inbox"),
    path("detail/<int:pk>/", views.detail, name="detail"),
    path("new/<int:item_pk>/", views.new_conversation, name="new")
]

core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("contact/", views.contact, name="contact"),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = "dashboard"

urlpatterns = [
    path("", views.index, name="index")
]

item/urls.py
from django.urls import path

from . import views

app_name = "item"

urlpatterns = [
    path("", views.browse, name="browse"),
    path("<int:pk>/", views.detail, name="detail"),
    path("new/", views.new, name="new"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/edit/", views.edit, name="edit"),
]

puddle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls")),
    path("items/", include("item.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("inbox/", include("conversation.urls")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Your Username",
                "class": "w-full py-4 px-6 rounded-md",
            }
        )
    )
    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Your Email Address",
                "class": "w-full py-4 px-6 rounded-md",
            }
        )
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Your Password",
                "class": "w-full py-4 px-6 rounded-md",
            }
        )
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Confirm Your Password",
                "class": "w-full py-4 px-6 rounded-md",
            }
        )
    )


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Your Username",
                "class": "w-full py-4 px-6 rounded-md",
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Your Password",
                "class": "w-full py-4 px-6 rounded-md",
            }
        )
    )

core/views.py
import random
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import LoginView

from item.models import Category, Item
from .forms import SignUpForm, LoginForm

# Create your views here.


def index(request):
    items = Item.objects.filter(is_sold=False)
    sampled_items = random.sample(list(items), min(6, len(items)))
    categories = Category.objects.all()

    return render(
        request,
        "core/index.html",
        {"items": sampled_items, "categories": categories},
    )


def contact(request):
    return render(request, "core/contact.html")


def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect("core:login")
    else:
        form = SignUpForm()

    return render(request, "core/signup.html", {"form": form})


class LoginView(LoginView):
    form_class = LoginForm
    template_name = "core/login.html"


def logout_user(request):
    logout(request)
    return redirect("core:index")

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}

      {% endblock %}| Puddle
    </title>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body>
    <header class="border-b border-gray-200">
      <nav class="max-w-7xl mx-auto p-6 flex justify-between items-center">
        <a href="/" class="text-2xl font-semibold">Puddle</a>
        <ul class="flex space-x-6">
          <li>
            <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">New Item</a>
          </li>
          <li>
            <a href="{% url 'item:browse' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>
          </li>
          {% if request.user.is_authenticated %}
            <li>
              <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
            </li>
            <li>
              <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
            </li>
            <li>
              <a href="{% url 'core:logout' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log Out</a>
            </li>
          {% else %}
            <li>
              <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign Up</a>
            </li>
            <li>
              <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log In</a>
            </li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main class="max-w-7xl mx-auto">
      <div class="py-12 px-6">
        {% block content %}

        {% endblock %}
      </div>
    </main>

    <footer class="bg-gray-800">
      <div class="max-w-7xl mx-auto p-6 flex justify-between">
        <div class="w-2/3 pr-10 text-left">
          <h3 class="mb-5 font-semibold text-gray-400">About</h3>
          <p class="text-lg text-gray-500">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Illum, at!</p>
        </div>
        <div class="w-1/3 text-right">
          <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
          <ul class="space-y-2">
            <li>
              <a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a>
            </li>
            <li>
              <a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a>
            </li>
            <li>
              <a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy Policy</a>
            </li>
            <li>
              <a href="#" class="text-lg text-teal-500 hover:text-teal-700">Terms of Use</a>
            </li>
          </ul>
        </div>
      </div>
    </footer>
  </body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}
  Contact
{% endblock %}

{% block content %}
  <h1>The contact page</h1>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}
  Welcome
{% endblock %}

{% block content %}
  <div class="flex flex-col gap-6">
    <div class="p-6 bg-gray-100 rounded-xl">
      <h2 class="mb-12 text-3xl text-center text-gray-700">Newest Items</h2>
      <div class="grid grid-cols-3 gap-3">
        {% for item in items %}
          <div>
            <a href="{% url 'item:detail' item.id %}">
              <div>
                <img src="{{ item.image.url }}" class="rounded-t-xl" alt="" />
              </div>
              <div class="p-6 bg-white rounded-b-xl">
                <h2 class="text-2xl">{{ item.name }}</h2>
                <p class="text-gray-400">Price: ৳{{ item.price }}</p>
              </div>
            </a>
          </div>
        {% endfor %}
      </div>
    </div>

    <div class="p-6 bg-gray-100 rounded-xl">
      <h2 class="mb-12 text-3xl text-center text-gray-700">Categories</h2>
      <div class="grid grid-cols-3 gap-3">
        {% for category in categories %}
          <div>
            <a href="#">
              <div class="p-6 bg-white rounded-b-xl">
                <h2 class="text-2xl">{{ category.name }}</h2>
                <p class="text-gray-400">
                  {{ category.items.count }} {% if category.items.count <= 1 %}
                    Item
                  {% else %}
                    Items
                  {% endif %}
                </p>
              </div>
            </a>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}
  Log In
{% endblock %}

{% block content %}
  <div class="w-1/2 p-6 mx-auto bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl text-center">Log In</h1>

    <form action="." method="post">
      {% csrf_token %}

      <div class="mb-3">{{ form.username }}</div>
      <div class="mb-3">{{ form.password }}</div>

      {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
          {% for field in form %}
            {{ field.errors }}
          {% endfor %}
          {{ form.non_field_errors }}
        </div>
      {% endif %}

      <button class="mt-6 py-4 w-full text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
  </div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}
  Sign Up
{% endblock %}

{% block content %}
  <div class="w-1/2 p-6 mx-auto bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl text-center">Sign Up</h1>

    <form action="." method="post">
      {% csrf_token %}

      <div class="mb-3">
        {{ form.username }}
      </div>
      <div class="mb-3">
        {{ form.email }}
      </div>
      <div class="mb-3">
        {{ form.password1 }}
      </div>
      <div class="mb-3">
        {{ form.password2 }}
      </div>

      {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
          {% for field in form %}
            {{ field.errors }}
          {% endfor %}
          {{ from.non_field_errors }}
        </div>
      {% endif %}

      <button class="mt-6 py-4 w-full text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
  </div>
{% endblock %}